services:
  - type: web
    name: cais-api
    runtime: node
    rootDir: back-end
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://txrmhhvwmlvdevqrfppo.supabase.co
      - key: CORS_ORIGIN
        value: https://cais-frontend-two.vercel.app
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
